### PR TITLE
Add src-dir option, see commit comment

### PR DESCRIPTION
**Pull request by viatoriche**

### CODE REVIEW

**Comment by kmmbvnr** [comment]
What is the reason for that?

**Comment by viatoriche** [comment]
Yes, but don't work. You aure wrong.
see demo project: https://github.com/viatoriche/test_django_jenkins

(test_django_jenkins)viatoriche@mouse:~/Dropbox/coding/test_django_jenkins$ ./manage.py jenkins apps
/home/viatoriche/Dropbox/coding/envs/test_django_jenkins/local/lib/python2.7/site-packages/django_jenkins/tasks/with_coverage.py:5: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

/home/viatoriche/Dropbox/coding/envs/test_django_jenkins/local/lib/python2.7/site-packages/django_jenkins/runner.py:10: RemovedInDjango19Warning: django.utils.unittest will be removed in Django 1.9.
  from django.utils.unittest import TextTestResult, TextTestRunner

Creating test database for alias 'default'...

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Destroying test database for alias 'default'...
/home/viatoriche/Dropbox/coding/envs/test_django_jenkins/local/lib/python2.7/site-packages/django_jenkins/management/commands/jenkins.py:194: UserWarning: No app found for test: apps
  warnings.warn('No app found for test: {0}'.format(test_label))

Executing django_jenkins.tasks.run_pep8...
Executing django_jenkins.tasks.run_pyflakes...
Done
(test_django_jenkins)viatoriche@mouse:~/Dropbox/coding/test_django_jenkins$ cat reports/pep8.report 
(test_django_jenkins)viatoriche@mouse:~/Dropbox/coding/test_django_jenkins$ cat reports/pyflakes.report 

empty files, but: 
if run manage.py jenkins
reports are not empty

I use --src-dir in my project, and I am happy, but must use my fork :c

**Comment by kmmbvnr** [comment]
i don't mean that it works. I mean, your solution for the problem is wrong.

**Comment by viatoriche** [comment]
Ok, I will think about other solutions.

**Comment by viatoriche** [comment]
I solve this issue in my project

1. Set PROJECT_APPS
2. Write class (CITestSuiteRunner)
where override build_suite method, where add:
if test_labels is None or not test_labels:
            test_labels = getattr(settings, 'PROJECT_APPS', test_labels)
3. And all works!

**Pull request closed without merging**
