### PR TITLE
fixes #276

### LINKED ISSUE #276: TypeError: unorderable types: str() > int() with python 3.4 and Django 1.8
(PR with fix follows)

Hi,

I ran into this problem while running against the new Django 1.8

Here is a full trace:

 $ ./manage.py jenkins
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/emma/dev/polla/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/emma/dev/polla/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/emma/dev/polla/venv/lib/python3.4/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/emma/dev/polla/venv/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/emma/dev/polla/venv/lib/python3.4/site-packages/django/core/management/commands/test.py", line 65, in execute
    if options['verbosity'] > 0:
TypeError: unorderable types: str() > int()

### PR DESCRIPTION
**Pull request by nanuxbe**
Changed --verbosity values to int instead of str
fixes #276

### CODE REVIEW

**Comment by nanuxbe** [comment]
I used int arguments as in https://github.com/django/django/blob/stable/1.8.x/django/core/management/base.py#L332
as I didn't see a check for `self.use_argparse` although it might probably be useful to do one and act accordingly to stay compatible with older versions of Django but that's not my call to make.

**Comment by kmmbvnr** [comment]
could you modify tox.ini also for checking that unde django 1.8?

**Comment by nanuxbe** [comment]
Sure.
Would creating a requirements-1.8.txt file and using that in a new environment in tox.ini be ok? Running 1.8 yields quite a different set of requirements compared to the current file. Here they are:
Django==1.8
astroid==1.3.4
coverage==3.7.1
flake8==2.4.0
logilab-common==0.63.2
mccabe==0.3
pep8==1.6.2
pyflakes==0.8.1
pylint==1.4.1
pylint-django==0.6
pylint-plugin-utils==0.2.3
selenium==2.45.0
six==1.9.0

**Comment by kmmbvnr** [comment]
mm, i think just new testenv section inside tox.ini would be ok

**Comment by nanuxbe** [comment]
Done.
Note that none of the tox configs runs on my computer (either before or after this PR) so I can't be certain of anything ;-)

**Comment by kmmbvnr** [comment]
What kind of problems do you have with tox?

**Comment by nanuxbe** [comment]
Mostly that I don't have all those python env's on my dev machine (I run 2.7 and 3.4) I have more on my jenkins server if I do need them.
And if I update the ini file to run 3.4, it  tells me it doesn't know --liveserver (which is probably another issue related to the changes in Django 1.8 but which is not the same as this one)

**Pull request closed without merging**
